[package]
name = "primitives-evm-tracing-ext"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
primitives-evm-tracing-events = { path = "../primitives-evm-tracing-events", default-features = false }

codec = { workspace = true }
sp-runtime-interface = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
  "codec/std",
  "primitives-evm-tracing-events/std",
  "sp-runtime-interface/std",
  "sp-std/std",
]
