
//! Autogenerated weights for `pallet_bioauth`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-11, STEPS: `2`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/debug/humanode-peer
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_bioauth
// --extrinsic
// *
// --steps
// 2
// --repeat
// 10
// --output
// ./

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_bioauth`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_bioauth::WeightInfo for WeightInfo<T> {
	// Storage: Bioauth RobonodePublicKey (r:1 w:0)
	// Storage: Bioauth ConsumedAuthTicketNonces (r:1 w:1)
	// Storage: Bioauth ActiveAuthentications (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	fn authenticate(_i: u32, ) -> Weight {
		(595_778_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
