unstable_features = true

format_macro_matchers = true
format_macro_bodies = true

group_imports = "StdExternalCrate"

report_fixme = "Unnumbered"
report_todo = "Unnumbered"

format_code_in_doc_comments = true

use_field_init_shorthand = true
