exclude = ["target/**"]
include = ["**/*.toml"]

[schema]
path = "taplo://taplo.toml"

[formatting]
reorder_keys = false
column_width = 120

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "build-dependencies", "features"]

[rule.formatting]
reorder_keys = true
array_auto_collapse = false
