[package]
name = "vesting-logic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
vesting-schedule = { version = "0.1", path = "../vesting-schedule", default-features = false }

frame-support = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "master" }

[features]
default = ["std"]
std = [
  "frame-support/std",
  "vesting-schedule/std",
]
