#!/bin/bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

PROJECT="${1?Specify a github project to be updated}"

cargo metadata --format-version 1 |
  jq \
    --arg src "git+https://github.com/$PROJECT" \
    '.packages | map(select(.source | tostring | startswith($src))) | map({ name: .name, version: .version, source: .source, id: .id })'
