[package]
name = "pallet-evm-precompiles-constant-accounts"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { workspace = true, package = "parity-scale-codec", features = ["derive"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-evm = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }

[dev-dependencies]
fp-evm = { workspace = true }
hex-literal = { workspace = true }
pallet-balances = { workspace = true, features = ["default"] }
pallet-evm-balances = { workspace = true, features = ["default"] }
pallet-evm-system = { workspace = true, features = ["default"] }
pallet-timestamp = { workspace = true, features = ["default"] }

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-balances/std",
  "pallet-evm/std",
  "pallet-evm-balances/std",
  "pallet-evm-system/std",
  "scale-info/std",
  "sp-core/std",
]
try-runtime = ["frame-support/try-runtime", "frame-system/try-runtime", "pallet-evm/try-runtime"]
