#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
cd "$SCRIPT_DIR/../../.."

TESTS_QUALIFIER="${1?Provide tests qualifier parameter as the first arguemnt}"
shift

HUMANODE_PEER_PATH="${1?Provide the path to the humanode peer as the second arguemnt}"
shift

HUMANODE_PEER_PATH="$(realpath -s "$HUMANODE_PEER_PATH")"
export HUMANODE_PEER_PATH

if [[ "$TESTS_QUALIFIER" == "base" ]]; then
  exec yarn utils/e2e-tests/ts test "$@"
fi
