[package]
name = "primitives-liveness-data"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "2", features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[features]
