#!/bin/bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

cargo metadata --format-version 1 |
  jq \
    --arg src "git+https://github.com/humanode-network/substrate" \
    '.packages | map(select(.source | tostring | startswith($src))) | map({ name: .name, version: .version, source: .source, id: .id })'
