#!/bin/bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

PACKAGES="$(utils/substrate-fork-crates/list | jq -r '.[].name')"

ARGS=()
for PACKAGE in $PACKAGES; do
  ARGS+=(-p "$PACKAGE")
done

cargo update "${ARGS[@]}"
