#!/bin/bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

if [[ $# -eq 0 ]] ; then
    echo "Specify a project name to be updated"
    exit 1
fi

PROJECT="$1"

PACKAGES="$(utils/update-fork-crates/list $PROJECT | jq -r '.[] | "\(.name):\(.version)"')"

ARGS=()
for PACKAGE in $PACKAGES; do
  ARGS+=(-p "$PACKAGE")
done

cargo update "${ARGS[@]}"
