[package]
name = "robonode-client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tokio = { workspace = true, features = ["full"] }
wiremock = { workspace = true }
