#!/bin/bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

# Run all e2e tests.
for TESTFILE in utils/e2e-tests/tests/*.sh; do
  printf "=> Running test %s\n" "$TESTFILE" >&2
  "$TESTFILE" "$@"
  printf "=> Test %s passed\n" "$TESTFILE" >&2
done
