[package]
name = "primitives-auth-ticket"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { workspace = true, package = "parity-scale-codec", features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"], optional = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = ["serde/std", "codec/std", "sp-std/std", "scale-info/std"]
