[package]
name = "primitives-auth-ticket"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde = { version = "1", features = ["derive"], optional = true }
sp-std = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "locked/humanode-2022-11-23" }

[features]
default = ["std"]
std = ["serde", "codec/std", "sp-std/std", "scale-info/std"]
