[package]
name = "primitives-auth-ticket"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { workspace = true, package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
serde = { workspace = true, features = ["derive"], optional = true }
sp-std = { workspace = true, default-features = false }

[features]
default = ["std"]
std = ["serde", "codec/std", "sp-std/std", "scale-info/std"]
