# syntax=docker/dockerfile:1.2

ARG BASE

FROM ${BASE}

RUN apt-get update \
  && apt-get install -y \
  libssl1.1 \
  ca-certificates \
  jq \
  curl \
  && rm -rf /var/lib/apt/lists/*

COPY . /usr/local/bin
