[package]
name = "ngrok-api"
version = "0.1.0"
edition = "2021"
authors = ["Humanode Team <core@humanode.io>"]
publish = false

[dependencies]
http = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true, features = ["default"] }
serde = { workspace = true, features = ["default"] }
thiserror = { workspace = true, optional = true }
url = { workspace = true, optional = true }

[features]
client = ["http", "url", "thiserror", "reqwest"]
default = ["client", "http"]
