[package]
name = "ngrok-api"
version = "0.1.0"
edition = "2021"
authors = ["Humanode Team <core@humanode.io>"]
publish = false

[dependencies]
async-trait = { version = "0.1", optional = true }
http = { version = "0.2", optional = true }
http-body = { version = "0.4", optional = true }
reqwest = { version = "0.11", optional = true }
serde = "1"
serde_json = "1"
thiserror = { version = "1", optional = true }
url = { version = "2", optional = true }

[features]
default = ["client", "http"]
client = ["http", "url", "http-body", "thiserror", "async-trait", "reqwest"]
