[package]
name = "eip712-common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
primitives-ethereum = { path = "../primitives-ethereum", default-features = false }

sp-core-hashing-proc-macro = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = ["primitives-ethereum/std", "sp-core/std", "sp-io/std", "sp-std/std"]
