[package]
name = "utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
humanode-runtime = { version = "0.1", path = "../humanode-runtime" }

pallet-im-online = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-consensus-babe = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-finality-grandpa = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/humanode-network/substrate", branch = "master" }
