[package]
name = "primitives-ethereum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { workspace = true, package = "parity-scale-codec", features = ["derive"] }
frame-support = { workspace = true }
rustc-hex = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, optional = true, features = ["default"] }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-support/std",
  "rustc-hex/std",
  "scale-info/std",
  "serde/std",
  "serde_json/std",
]
