[package]
name = "primitives-ethereum"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "locked/polkadot-v0.9.38" }
frame-system = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "locked/polkadot-v0.9.38" }
rustc-hex = { version = "2.1.0", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1", optional = true }

[dev-dependencies]
serde_json = "1"

[features]
default = ["std"]
std = ["codec/std", "frame-support/std", "frame-system/std", "rustc-hex/std", "scale-info/std", "serde"]
