[settings]
enable_tracing = false

[relaychain]
default_command = "{{HUMANODE_PEER_PATH}}"
chain = "local"
chain_spec_command = "{{HUMANODE_PEER_PATH}} build-spec --chain local --raw > ./zombienet-test/local-raw.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "batumi"
  validator = true
