[target.'cfg(all())']
rustflags = [
  "-Dunsafe_code",
  "-Wclippy::all",
  "-Wclippy::cargo",
  "-Wmissing_docs",
  "-Wclippy::missing_docs_in_private_items",
  "-Wclippy::clone_on_ref_ptr",
  "-Wclippy::await_holding_lock",
  "-Wclippy::cloned_instead_of_copied",
  "-Wclippy::copy_iterator",
  "-Wclippy::doc_link_with_quotes",
  "-Wclippy::doc_markdown",
  "-Wclippy::expl_impl_clone_on_copy",
  "-Wclippy::explicit_deref_methods",
  "-Wclippy::explicit_into_iter_loop",
  "-Wclippy::explicit_iter_loop",
  "-Wclippy::filter_map_next",
  "-Wclippy::flat_map_option",
  "-Wclippy::inefficient_to_string",
  "-Wclippy::match_same_arms",
  "-Wclippy::unsafe_derive_deserialize",
  "-Wclippy::match_on_vec_items",
  # A few exceptions.
  "-Aclippy::cargo-common-metadata",
  "-Aclippy::derive-partial-eq-without-eq",
]
