[target.'cfg(all())']
rustflags = [
  "-Dunsafe_code",
  "-Wclippy::all",
  "-Wclippy::cargo",
  "-Wmissing_docs",
  "-Wclippy::missing_docs_in_private_items",
  "-Wclippy::clone_on_ref_ptr",
  "-Wclippy::await_holding_lock",
  "-Wclippy::integer_arithmetic",
  "-Wclippy::float_arithmetic",
  "-Wclippy::modulo_arithmetic",
  "-Wclippy::cast_lossless",
  "-Wclippy::cast_possible_truncation",
  "-Wclippy::cast_possible_wrap",
  "-Wclippy::cast_precision_loss",
  "-Wclippy::cast_sign_loss",
  "-Wclippy::checked_conversions",
  "-Wclippy::float_cmp",
  # A few exceptions.
  "-Aclippy::cargo-common-metadata",
  "-Aclippy::derive-partial-eq-without-eq",
]
