[package]
name = "native-chain-id"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chain-properties-api = { version = "0.1", path = "../chain-properties-api" }

sp-api = { git = "https://github.com/humanode-network/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/humanode-network/substrate", branch = "master" }
