[package]
name = "precompile-utils-macro"
authors = ["PureStake"]
description = ""
edition = "2021"
version = "0.1.0"
publish = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
num_enum = { version = "0.5.3", default-features = false }                       # special case, exlucded from workspace dependencies
proc-macro2 = { workspace = true }
quote = { workspace = true }
sha3 = "0.9"                                                                     # special case, exlucded from workspace dependencies
syn = { workspace = true, features = ["extra-traits", "fold", "full", "visit"] }
