[package]
name = "pallet-evm-balances"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
scale-info = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
pallet-evm-system = { path = "../pallet-evm-system", features = ["default"] }

fp-evm = { workspace = true }
pallet-evm = { workspace = true }
pallet-timestamp = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }

[features]
default = ["std"]
std = [
  "codec/std",
  "fp-evm/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-evm-system/std",
  "pallet-evm/std",
  "pallet-timestamp/std",
  "scale-info/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]
try-runtime = [
  "frame-support/try-runtime",
  "frame-system/try-runtime",
  "pallet-evm-system/try-runtime",
  "pallet-evm/try-runtime",
  "pallet-timestamp/try-runtime",
  "sp-runtime/try-runtime",
]
