[package]
name = "keystore-bioauth-account-id"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
frame-system = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "locked/polkadot-v0.9.36" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-application-crypto = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "locked/polkadot-v0.9.36" }
sp-core = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "locked/polkadot-v0.9.36" }
sp-runtime = { default-features = false, git = "https://github.com/humanode-network/substrate", branch = "locked/polkadot-v0.9.36" }

[features]
default = ["std"]
std = ["codec/std", "frame-system/std", "scale-info/std", "sp-application-crypto/std", "sp-core/std", "sp-runtime/std"]
