#!/bin/bash
set -euo pipefail

LOG_DIR="/tmp/runchain"
NODES_DATA_DIR="/tmp/runchain"

NODES=()

while [[ "$#" -gt 1 ]]; do
  case "$1" in
  --base-only)
    BASE_ONLY=true
    shift
    ;;
  --)
    CALL_VALID=true
    shift
    break
    ;;
  *)
    NODES+=("$1")
    shift
    ;;
  esac
done

if [[ "${CALL_VALID:-}" != "true" ]]; then
  printf "Usage: %s alice bob charlie ... -- target/debug/humanode-peer\n" "$0" >&2
  exit 1
fi

P2P_PORT=30333
RPC_HTTP_PORT=9933
RPC_WS_PORT=9944

trap 'pkill -P $$' EXIT

for NODE in "${NODES[@]}"; do
  FLAG="--${NODE}"
  LOG_FILE="$LOG_DIR/$NODE.log"

  ARGS=(
    --base-path "$NODES_DATA_DIR/$NODE"
  )

  if [[ "${BASE_ONLY:-"false"}" != "true" ]]; then
    ARGS+=(
      --port "$P2P_PORT"
      --rpc-port "$RPC_HTTP_PORT"
      --ws-port "$RPC_WS_PORT"
      "$FLAG"
    )
  fi

  {
    "$@" "${ARGS[@]}" 2>&1 | tee "$LOG_FILE"
  } &

  NODE_PID="$!"

  printf "node: %s\tlog: %s\tpid: %d\n" "$NODE" "$LOG_FILE" "$NODE_PID"

  ((P2P_PORT = P2P_PORT + 1))
  ((RPC_HTTP_PORT = RPC_HTTP_PORT + 1))
  ((RPC_WS_PORT = RPC_WS_PORT + 1))
done

wait
