[package]
name = "precompile-evm-balances-erc20"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pallet-token-wrapper = { path = "../pallet-token-wrapper", default-features = false }
precompile-utils = { path = "../precompile-utils", default-features = false }

codec = { workspace = true, package = "parity-scale-codec", features = ["derive"] }
fp-evm = { workspace = true }
frame-support = { workspace = true }
num_enum = { workspace = true }
pallet-evm = { workspace = true }
pallet-evm-balances = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }

[dev-dependencies]
precompile-utils = { path = "../precompile-utils", features = ["testing"] }

frame-system = { workspace = true }
hex-literal = { workspace = true }
pallet-balances = { workspace = true, features = ["default"] }
pallet-evm = { workspace = true }
pallet-evm-system = { workspace = true, features = ["default"] }
pallet-timestamp = { workspace = true, features = ["default"] }

[features]
default = ["std"]
std = [
  "codec/std",
  "fp-evm/std",
  "frame-support/std",
  "frame-system/std",
  "num_enum/std",
  "pallet-balances/std",
  "pallet-evm-balances/std",
  "pallet-evm-system/std",
  "pallet-evm/std",
  "pallet-timestamp/std",
  "pallet-token-wrapper/std",
  "precompile-utils/std",
  "scale-info/std",
  "sp-core/std",
]
