// DO NOT EDIT! This file is generated by "utils/weights/benchmark-all" command.
//! Computed benchmarks.
//! Mode: "dev"

pub mod frame_system;
pub mod pallet_balances;
pub mod pallet_bioauth;
pub mod pallet_evm_accounts_mapping;
pub mod pallet_fixed_validators_set;
pub mod pallet_humanode_session;
pub mod pallet_im_online;
pub mod pallet_multisig;
pub mod pallet_native_to_evm_swap;
pub mod pallet_sudo;
pub mod pallet_timestamp;
pub mod pallet_token_claims;
pub mod pallet_utility;
pub mod pallet_vesting;
