// DO NOT EDIT!
//! Autogenerated weights for `pallet_fixed_validators_set`

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_fixed_validators_set`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_fixed_validators_set::WeightInfo for WeightInfo<T> {
  fn update_set() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `0`
    //  Estimated: `0`
    // Minimum execution time: 33_000_000 picoseconds.
    Weight::from_parts(33_000_000, 0)
      .saturating_add(T::DbWeight::get().writes(1))
  }
}
