// DO NOT EDIT!
//! Autogenerated weights for `pallet_vesting`

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_vesting`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_vesting::WeightInfo for WeightInfo<T> {
  fn unlock() -> Weight {
    // Minimum execution time: 35_000 nanoseconds.
    Weight::from_ref_time(35_000_000)
      .saturating_add(T::DbWeight::get().reads(5))
      .saturating_add(T::DbWeight::get().writes(3))
  }
  fn update_schedule() -> Weight {
    // Minimum execution time: 38_000 nanoseconds.
    Weight::from_ref_time(38_000_000)
      .saturating_add(T::DbWeight::get().reads(5))
      .saturating_add(T::DbWeight::get().writes(3))
  }
}
