[package]
name = "precompile-native-currency"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pallet-erc20-support = { path = "../pallet-erc20-support", default-features = false }
pallet-evm-balances = { path = "../pallet-evm-balances", default-features = false }
precompile-utils = { path = "../precompile-utils", default-features = false }

codec = { workspace = true, features = ["derive"] }
fp-evm = { workspace = true }
frame-support = { workspace = true }
num_enum = { workspace = true }
pallet-evm = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }

[dev-dependencies]
pallet-evm-system = { path = "../pallet-evm-system", features = ["default"] }
precompile-utils = { path = "../precompile-utils", features = ["testing"] }

frame-system = { workspace = true }
hex-literal = { workspace = true }
pallet-balances = { workspace = true, features = ["default"] }
pallet-evm = { workspace = true }
pallet-timestamp = { workspace = true, features = ["default"] }

[features]
default = ["std"]
std = [
  "codec/std",
  "fp-evm/std",
  "frame-support/std",
  "frame-system/std",
  "num_enum/std",
  "pallet-balances/std",
  "pallet-erc20-support/std",
  "pallet-evm-balances/std",
  "pallet-evm-system/std",
  "pallet-evm/std",
  "pallet-timestamp/std",
  "precompile-utils/std",
  "scale-info/std",
  "sp-core/std",
]
