[package]
name = "humanode-rpc-errors"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }
serde_json = "1"
thiserror = "1"
