[package]
name = "rpc-validator-key-logic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bioauth-keys = { path = "../bioauth-keys" }

jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
