[package]
name = "rpc-deny-unsafe"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sc-rpc-api = { git = "https://github.com/humanode-network/substrate", branch = "locked/polkadot-v0.9.38" }
