name: toml

on:
  push:
    branches:
      - '**'
      - '!gh-readonly-queue/**'
  merge_group:
  schedule:
    - cron: '0 20 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.event_name != 'merge_group' }}

jobs:

  taplo:
    name: taplo
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install taplo
        run: >
          curl -sSL "https://github.com/tamasfe/taplo/releases/download/0.8.0/taplo-linux-x86_64.gz" |
            zcat > /usr/local/bin/taplo \
          && chmod +x /usr/local/bin/taplo

      - name: Check TOML files format
        run: taplo format --check

  cargo-sort:
    name: cargo-sort
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo-sort
        run: >
          curl -sSL "https://github.com/DevinR528/cargo-sort/releases/download/v1.0.9/cargo-sort-x86_64-unknown-linux-gnu.tar.gz" |
            sudo tar -xzvf - -C /usr/local/bin

      - name: Lint TOML files
        run: cargo-sort -cwg
