name: toml

on:
  push:
  schedule:
    - cron: '0 20 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  taplo:
    name: taplo
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check TOML files format
        run: npx @taplo/cli@0.4.0 format --check
        env:
          npm_config_yes: "true"

  cargo-sort:
    name: cargo-sort
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cargo-sort
        run: >
          curl -sSL "https://github.com/DevinR528/cargo-sort/releases/download/v1.0.5/cargo-sort-x86_64-unknown-linux-gnu.tar.gz" |
            sudo tar -xzvf - -C /usr/local/bin

      - name: Lint TOML files
        run: cargo-sort -cwg
