[package]
name = "devutil-auth-ticket"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
primitives-auth-ticket = { version = "0.1", path = "../primitives-auth-ticket" }
robonode-crypto = { version = "0.1", path = "../robonode-crypto" }

anyhow = "1"
hex = "0.4"
