[package]
name = "devutil-auth-ticket"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
primitives-auth-ticket = { path = "../primitives-auth-ticket" }
robonode-crypto = { path = "../robonode-crypto" }

anyhow = { workspace = true }
hex = { workspace = true }
